//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handheld_Control_Panel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public string systemAccent {
            get {
                return ((string)(this["systemAccent"]));
            }
            set {
                this["systemAccent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MMIO+MSR")]
        public string IntelMMIOMSR {
            get {
                return ((string)(this["IntelMMIOMSR"]));
            }
            set {
                this["IntelMMIOMSR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int minTDP {
            get {
                return ((int)(this["minTDP"]));
            }
            set {
                this["minTDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int maxTDP {
            get {
                return ((int)(this["maxTDP"]));
            }
            set {
                this["maxTDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkUpdatesAtStartUp {
            get {
                return ((bool)(this["checkUpdatesAtStartUp"]));
            }
            set {
                this["checkUpdatesAtStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int maxGPUCLK {
            get {
                return ((int)(this["maxGPUCLK"]));
            }
            set {
                this["maxGPUCLK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool combineTDP {
            get {
                return ((bool)(this["combineTDP"]));
            }
            set {
                this["combineTDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoStartRTSS {
            get {
                return ((bool)(this["autoStartRTSS"]));
            }
            set {
                this["autoStartRTSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string SystemTheme {
            get {
                return ((string)(this["SystemTheme"]));
            }
            set {
                this["SystemTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoApplySetTDP {
            get {
                return ((bool)(this["autoApplySetTDP"]));
            }
            set {
                this["autoApplySetTDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool dockWindowRight {
            get {
                return ((bool)(this["dockWindowRight"]));
            }
            set {
                this["dockWindowRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cpuEfficiencyMode {
            get {
                return ((bool)(this["cpuEfficiencyMode"]));
            }
            set {
                this["cpuEfficiencyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime lastCheckUpdate {
            get {
                return ((global::System.DateTime)(this["lastCheckUpdate"]));
            }
            set {
                this["lastCheckUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string directorySteam {
            get {
                return ((string)(this["directorySteam"]));
            }
            set {
                this["directorySteam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string directoryPlaynite {
            get {
                return ((string)(this["directoryPlaynite"]));
            }
            set {
                this["directoryPlaynite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string directoryEpicGames {
            get {
                return ((string)(this["directoryEpicGames"]));
            }
            set {
                this["directoryEpicGames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int maxRTSSFPSLimit {
            get {
                return ((int)(this["maxRTSSFPSLimit"]));
            }
            set {
                this["maxRTSSFPSLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string mouseModeHIDHide {
            get {
                return ((string)(this["mouseModeHIDHide"]));
            }
            set {
                this["mouseModeHIDHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GUID {
            get {
                return ((string)(this["GUID"]));
            }
            set {
                this["GUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string instanceID {
            get {
                return ((string)(this["instanceID"]));
            }
            set {
                this["instanceID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Usercontrol_Bluetooth1;Usercontrol_Wifi1;Usercontrol_MouseMode1;Usercontrol_Controller0;Divider1;Usercontrol_Volume1;Usercontrol_VolumeMute1;Usercontrol_Brightness1;Divider1;Usercontrol_Resolution1;Usercontrol_RefreshRate1;Usercontrol_Scaling1;Usercontrol_FPSLimit1;Divider1;Usercontrol_TDP1;Usercontrol_TDP21;Usercontrol_EPP1;Usercontrol_ActiveCores1;Usercontrol_MaxCPUFrequency1;Usercontrol_GPUCLK1;Divider1;UserControl_FanControl1;")]
        public string qamUserControls {
            get {
                return ((string)(this["qamUserControls"]));
            }
            set {
                this["qamUserControls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableNotifications {
            get {
                return ((bool)(this["enableNotifications"]));
            }
            set {
                this["enableNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sort_Method_ProfileName")]
        public string appSortMethod {
            get {
                return ((string)(this["appSortMethod"]));
            }
            set {
                this["appSortMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public double joystickDeadzone {
            get {
                return ((double)(this["joystickDeadzone"]));
            }
            set {
                this["joystickDeadzone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fanCurveTemperature {
            get {
                return ((string)(this["fanCurveTemperature"]));
            }
            set {
                this["fanCurveTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fanCurvePackagePower {
            get {
                return ((string)(this["fanCurvePackagePower"]));
            }
            set {
                this["fanCurvePackagePower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool fanAutoModeTemp {
            get {
                return ((bool)(this["fanAutoModeTemp"]));
            }
            set {
                this["fanAutoModeTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool startAutoFan {
            get {
                return ((bool)(this["startAutoFan"]));
            }
            set {
                this["startAutoFan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool upgradeSettingsRequired {
            get {
                return ((bool)(this["upgradeSettingsRequired"]));
            }
            set {
                this["upgradeSettingsRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startSafeMode {
            get {
                return ((bool)(this["startSafeMode"]));
            }
            set {
                this["startSafeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\RivaTuner Statistics Server")]
        public string directoryRTSS {
            get {
                return ((string)(this["directoryRTSS"]));
            }
            set {
                this["directoryRTSS"] = value;
            }
        }
    }
}
